# Generated by Django 2.2 on 2020-07-02 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('checksum', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('online', 'Online Payment'), ('cod', 'Cash on Delivery')], max_length=120, null=True)),
                ('status', models.CharField(choices=[('unpaid', 'Payment not done.'), ('paid', 'Payment complete.')], default='unpaid', max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
